-- Populate icons/value using names from V24 to avoid markdown quoting issues
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Heimdall' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lady of the Lake' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Robin Hood: Master Thief' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Tunupa: Mountain God' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Fairy Protection' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Loki' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 7, updated_at = NOW() WHERE name = 'Wrath of Ra' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'Valkyrie Skeggjold' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 7, updated_at = NOW() WHERE name = 'Oni and Succubus' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 7, updated_at = NOW() WHERE name = 'Bodhisattva: Enlightened One' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 4, updated_at = NOW() WHERE name = 'Mystical Energy' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Charge into Battle!' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 4, updated_at = NOW() WHERE name = 'Subjugate the Meek' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 4, updated_at = NOW() WHERE name = 'Draconic Leadership' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Any-Power'], value = 5, updated_at = NOW() WHERE name = 'Lilith''''s Swarm' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Disorient Opponent' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Freya: Goddess of Protection' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Grim Reaper' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Gunnr: Battle Valkyrie' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Hades: Lord of the Underworld' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Legendary Escape' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Merlin''''s Magic' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Preternatural Healing' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Princess and the Pea' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Gemini' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Valkyrie Hildr: Select the Slain' AND character_name = 'Any Character' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Shepherd of the Damned' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 5, updated_at = NOW() WHERE name = 'Siphon Strike' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Weighing of the Heart' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Wither' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat', 'Brute Force'], value = 5, updated_at = NOW() WHERE name = 'Lord of the Sacred Land' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Book of the Dead' AND character_name = 'Anubis' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Head for Mexico' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat', 'Brute Force'], value = 5, updated_at = NOW() WHERE name = 'I''''ll Make You Famous' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Pals' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Quick Draw' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Reap the Whirlwind' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Regulators' AND character_name = 'Billy the Kid' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Never Set Foot on Dry Land' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ethnologist' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 6, updated_at = NOW() WHERE name = 'Silent Running' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ruthless Plunderer' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Nautilus' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 10, updated_at = NOW() WHERE name = 'Weapons of Wrath and Hatred' AND character_name = 'Captain Nemo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Janjong Duare Mintep' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'On the Razor''''s Edge' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Telepathic Resistance' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Sometimes Piracy is the Best Option' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 4, updated_at = NOW() WHERE name = 'T-Ray Gun' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Telepathic Training' AND character_name = 'Carson of Venus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Friend to Foe' AND character_name = 'Count of Monte Cristo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 4, updated_at = NOW() WHERE name = 'Jacopo' AND character_name = 'Count of Monte Cristo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Network of Thieves' AND character_name = 'Count of Monte Cristo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Surprise Swordsman' AND character_name = 'Count of Monte Cristo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Unlimited Resources' AND character_name = 'Count of Monte Cristo' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 2, updated_at = NOW() WHERE name = 'Don''''t Let it Get Away!' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Mob Mentality' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 7, updated_at = NOW() WHERE name = 'Strength in Numbers' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Swarm Them!' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 7, updated_at = NOW() WHERE name = 'Pitchforks and Torches' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 3, updated_at = NOW() WHERE name = 'Regent of the Crown' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Disrupting Supply Lines' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 8, updated_at = NOW() WHERE name = 'Union Power' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 7, updated_at = NOW() WHERE name = 'Online Cyber Attack' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ransom Your Secrets' AND character_name = 'Angry Mob' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ancient One' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Devoted Follower' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Distracting Intervention' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 3, updated_at = NOW() WHERE name = 'Network of Fanatics' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Call of Cthulhu' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Any-Power'], value = 11, updated_at = NOW() WHERE name = 'The Sleeper Awakens' AND character_name = 'Cthulhu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 4, updated_at = NOW() WHERE name = 'Warrior of Helium' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Diplomat to All Martians' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Fortune of Helium' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Head of Martian Science' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Protector of Barsoom' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Champions of Barsoom' AND character_name = 'Dejah Thoris' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 6, updated_at = NOW() WHERE name = 'All Chips on the Table' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Blackheath Rugby Star' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'British Army Surgeon' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 7, updated_at = NOW() WHERE name = 'English Gentleman' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Not a Bad Detective' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Always There for a Friend' AND character_name = 'Dr. Watson' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 5, updated_at = NOW() WHERE name = 'Crimson Restoration' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Veil of Deceit' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 5, updated_at = NOW() WHERE name = 'Lord of the Vampires' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Paralyzing Gaze' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'To the Last Man' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Undead Flesh' AND character_name = 'Dracula' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Decapitate' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Human Spine Whip' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Mark of the Headless' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 6, updated_at = NOW() WHERE name = 'Pumpkin Head' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Relentless Hessian' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 6, updated_at = NOW() WHERE name = 'Visage of Terror' AND character_name = 'Headless Horseman' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 4, updated_at = NOW() WHERE name = 'Sowing Chaos' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 6, updated_at = NOW() WHERE name = 'Great Club' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lion Skin Cloak' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 9, updated_at = NOW() WHERE name = 'Godly Prowess' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 7, updated_at = NOW() WHERE name = 'Protector of Mankind' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Slaying the Hydra' AND character_name = 'Hercules' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Didn''''t See It Coming' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 5, updated_at = NOW() WHERE name = 'Hidden Sociopath' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'I''''m In Your House' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 0, updated_at = NOW() WHERE name = 'I''''ve Murdered Before' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'One at a Time' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Run and Hide' AND character_name = 'Invisible Man' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 7, updated_at = NOW() WHERE name = 'Archimedes Q. Porter' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ethnoarchaeology' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 2, updated_at = NOW() WHERE name = 'Tenacious Pursuit' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lady of the Jungle' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 5, updated_at = NOW() WHERE name = 'Not Without My Friends' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Not a Damsel in Distress' AND character_name = 'Jane Porter' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Angelic Visions' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Burned at the Stake' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Early Feminist Leader' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Inspirational Leadership' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat', 'Intelligence'], value = 8, updated_at = NOW() WHERE name = 'Patron Saint of France' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Protection of Saint Michael' AND character_name = 'Joan of Arc' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Dotar Sojat' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Immortality' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Leap into the Fray' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lower Gravity' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Superhuman Endurance' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Any-Power'], value = 8, updated_at = NOW() WHERE name = 'Virginia Fighting Man' AND character_name = 'John Carter of Mars' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat'], value = 9, updated_at = NOW() WHERE name = 'Excalibur' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'King of Camelot' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Knights of the Round Table' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'Legendary Partnership' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Heavy is the Head' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lead From the Front' AND character_name = 'King Arthur' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 6, updated_at = NOW() WHERE name = 'John Clayton III' AND character_name = 'Korak' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 3, updated_at = NOW() WHERE name = 'Jungle Survival' AND character_name = 'Korak' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Like Father' AND character_name = 'Like Son' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Meriem and Jackie Clayton' AND character_name = 'Korak' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Son of the Jungle' AND character_name = 'Korak' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 4, updated_at = NOW() WHERE name = 'To the Death' AND character_name = 'Korak' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Chivalrous Protector' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'For Guinevere''''s Love' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat', 'Brute Force'], value = 5, updated_at = NOW() WHERE name = 'For the Queen!' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Knight of the Round Table' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Sword and Shield' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'True Strike' AND character_name = 'Lancelot' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 8, updated_at = NOW() WHERE name = '300' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Baptized in Combat' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 6, updated_at = NOW() WHERE name = 'For Sparta' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Give Them Nothing' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Greatest Soldiers in History' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Shield Phalanx' AND character_name = 'Leonidas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Archimedes' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ascendant Mage' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'For Camelot!' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Foretell the Future' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Transmogrification' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat'], value = 4, updated_at = NOW() WHERE name = 'Summon the Elements' AND character_name = 'Merlin' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Dracula''''s Telepathic Connection' AND character_name = 'Mina Harker' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Jonathan Harker' AND character_name = 'Solicitor' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 5, updated_at = NOW() WHERE name = 'Nocturnal Hunter' AND character_name = 'Mina Harker' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'The Hunger' AND character_name = 'Mina Harker' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Tracking Movements' AND character_name = 'Mina Harker' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Vampiric Celerity' AND character_name = 'Mina Harker' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Apprentice of Merlin' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Avalon''''s Warmth' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Duality' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 4, updated_at = NOW() WHERE name = 'Enchantress'''' Guile' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 3, updated_at = NOW() WHERE name = 'Shapeshifter''''s Guise' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Teleportation Circle' AND character_name = 'Morgan le Fay' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 6, updated_at = NOW() WHERE name = 'Overdose' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force', 'Intelligence'], value = 4, updated_at = NOW() WHERE name = 'Sadistic Tendencies' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Set Loose' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Serum' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 6, updated_at = NOW() WHERE name = 'Trample' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Victorian Sophisticant' AND character_name = 'Mr. Hyde' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 6, updated_at = NOW() WHERE name = 'Reclaim the Waters' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Form of Water' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Any-Power'], value = 7, updated_at = NOW() WHERE name = 'Poseidon''''s Might' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Rising Tides' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Trident' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Tsunami' AND character_name = 'Poseidon' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force', 'Intelligence'], value = 3, updated_at = NOW() WHERE name = 'Complex Criminal Scheme' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Criminal Mastermind' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Future Plans' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Mathematical Genius' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Napoleon of Crime' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 5, updated_at = NOW() WHERE name = 'Tactical Fighter' AND character_name = 'Professor Moriarty' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat', 'Intelligence'], value = 6, updated_at = NOW() WHERE name = 'Cult of Menevis Bull' AND character_name = 'Ra' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Eye of Sekhmet' AND character_name = 'Ra' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Healing Waters of the Nile' AND character_name = 'Ra' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Band of Merry Men' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Defender of the People' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 4, updated_at = NOW() WHERE name = 'Hero of Nottingham' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 3, updated_at = NOW() WHERE name = 'Master Archer' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Master Thief' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Steal From the Rich' AND character_name = 'Robin Hood' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 6, updated_at = NOW() WHERE name = 'Flaming Arrows' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 9, updated_at = NOW() WHERE name = 'I Command an Army' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Read the Bones' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Rule by Fear' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Squeeze the Commoners' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Taxes' AND character_name = 'Sheriff of Nottingham' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Battle of Wits' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Brilliant Deduction' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 5, updated_at = NOW() WHERE name = 'Irene Adler' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Logical Reasoning' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Probability Evaluation' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 4, updated_at = NOW() WHERE name = 'Unpredictable Mind' AND character_name = 'Sherlock Holmes' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Cloud Surfing' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 11, updated_at = NOW() WHERE name = 'Godly Strength' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Grasp of the Five Elements' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 6, updated_at = NOW() WHERE name = 'Staff of the Monkey King' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Stone Skin' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Transformation Trickery' AND character_name = 'Sun Wukong' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Avenging My Love' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Barsoomian Warrior & Statesman' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 6, updated_at = NOW() WHERE name = 'Four-Armed Warrior' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 6, updated_at = NOW() WHERE name = 'Jeddak of Thark' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Protector of the Incubator' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Sola' AND character_name = 'Tars Tarkas' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Emotional Senses' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Jungle Tactics' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Lord of the Jungle' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 7, updated_at = NOW() WHERE name = 'My Feet are Like Hands' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'Raised by Mangani Apes' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 5, updated_at = NOW() WHERE name = 'Deceptive Maneuver' AND character_name = 'Tarzan' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Ancient Wisdom' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 5, updated_at = NOW() WHERE name = 'Fury of the Desert' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 7, updated_at = NOW() WHERE name = 'Pharaoh of the Fourth Dynasty' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Reinvigorated by Fresh Organs' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 3, updated_at = NOW() WHERE name = 'Relentless Pursuit' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Eternal Journey' AND character_name = 'The Mummy' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'All For One' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 5, updated_at = NOW() WHERE name = 'Aramis' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'Athos' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat', 'Brute Force', 'Intelligence'], value = 8, updated_at = NOW() WHERE name = 'D''''Artagnan' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Brute Force'], value = 6, updated_at = NOW() WHERE name = 'Porthos' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Any-Power'], value = 5, updated_at = NOW() WHERE name = 'Valiant Charge' AND character_name = 'The Three Musketeers' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'From a Mile Away' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 6, updated_at = NOW() WHERE name = 'Futuristic Phaser' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'I''''ll Already Be Gone' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Knowledge of Tomorrow' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Harbinger''''s Warning' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'The Tomorrow Doctor' AND character_name = 'Time Traveler' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Doctor' AND character_name = 'Professor' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Monster Hunting Expert' AND character_name = 'Van Helsing' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy', 'Combat'], value = 6, updated_at = NOW() WHERE name = 'Crossbow Expert' AND character_name = 'Van Helsing' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 3, updated_at = NOW() WHERE name = 'Right Tools for the Job' AND character_name = 'Van Helsing' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Sacred Wafers from Amsterdam' AND character_name = 'Van Helsing' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 5, updated_at = NOW() WHERE name = 'World-Renowned Doctor' AND character_name = 'Van Helsing' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Abner Perry''''s Lab Assistant' AND character_name = 'Victory Harben' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Archery' AND character_name = 'Knives & Jiu-jitsu' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Chamston-Hedding Estate' AND character_name = 'Victory Harben' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Department of Theoretical Physics' AND character_name = 'Victory Harben' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Fires of Halos' AND character_name = 'Victory Harben' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 7, updated_at = NOW() WHERE name = 'Practical Physics' AND character_name = 'Victory Harben' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Aquaphobic' AND character_name = 'Wicked Witch' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 4, updated_at = NOW() WHERE name = 'Feared by All Witches' AND character_name = 'Wicked Witch' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'I Will Have Those Silver Shoes!' AND character_name = 'Wicked Witch' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 7, updated_at = NOW() WHERE name = 'One Eye' AND character_name = 'Wicked Witch' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Harness the Wind' AND character_name = 'Wicked Witch' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Wolves' AND character_name = 'Crows' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'A Jealous God' AND character_name = 'Zeus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Banishment' AND character_name = 'Zeus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Hera' AND character_name = 'Zeus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Law and Order' AND character_name = 'Zeus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Energy'], value = 9, updated_at = NOW() WHERE name = 'Thunderbolt' AND character_name = 'Zeus' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 2, updated_at = NOW() WHERE name = '3 Quick Strokes' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 7, updated_at = NOW() WHERE name = 'Elite Swordsmanship' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Master of Escape' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Combat'], value = 4, updated_at = NOW() WHERE name = 'Ancestral Rapier' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = ARRAY['Intelligence'], value = 7, updated_at = NOW() WHERE name = 'Riches of Don Diego de la Vega' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
UPDATE special_cards SET icons = NULL, value = NULL, updated_at = NOW() WHERE name = 'Riposte' AND character_name = 'Zorro' AND (icons IS NULL OR value IS NULL);
