-- Populate characters data from ERB characters markdown file
-- This migration inserts all 43 characters from the overpower-erb-characters.md file

INSERT INTO characters (id, name, universe, description, energy, combat, brute_force, intelligence, image_path, alternate_images) VALUES
('character_angry_mob_middle_ages', 'Angry Mob (Middle Ages)', 'ERB', 'Angry Mob (Middle Ages) character from ERB', 6, 4, 6, 1, 'characters/001_angry_mob_middle_ages.webp', ARRAY[]::TEXT[]),
('character_angry_mob_industrial_age', 'Angry Mob (Industrial Age)', 'ERB', 'Angry Mob (Industrial Age) character from ERB', 4, 5, 7, 3, 'characters/008_angry_mob_industrial_age.webp', ARRAY[]::TEXT[]),
('character_angry_mob_modern_age', 'Angry Mob (Modern Age)', 'ERB', 'Angry Mob (Modern Age) character from ERB', 5, 1, 8, 5, 'characters/011_angry_mob_modern_age.webp', ARRAY[]::TEXT[]),
('character_anubis', 'Anubis', 'ERB', 'Anubis character from ERB', 6, 2, 7, 5, 'characters/014_anubis.webp', ARRAY[]::TEXT[]),
('character_billy_the_kid', 'Billy the Kid', 'ERB', 'Billy the Kid character from ERB', 4, 7, 3, 4, 'characters/021_billy_the_kid.webp', ARRAY[]::TEXT[]),
('character_captain_nemo', 'Captain Nemo', 'ERB', 'Captain Nemo character from ERB', 3, 6, 3, 7, 'characters/028_captain_nemo.webp', ARRAY[]::TEXT[]),
('character_carson_of_venus', 'Carson of Venus', 'ERB', 'Carson of Venus character from ERB', 7, 5, 4, 7, 'characters/035_carson_of_venus.webp', ARRAY[]::TEXT[]),
('character_count_of_monte_cristo', 'Count of Monte Cristo', 'ERB', 'Count of Monte Cristo character from ERB', 1, 6, 3, 7, 'characters/042_count_of_monte_cristo.webp', ARRAY[]::TEXT[]),
('character_cthulhu', 'Cthulhu', 'ERB', 'Cthulhu character from ERB', 6, 1, 8, 7, 'characters/048_cthulhu.webp', ARRAY[]::TEXT[]),
('character_dejah_thoris', 'Dejah Thoris', 'ERB', 'Dejah Thoris character from ERB', 6, 6, 2, 3, 'characters/055_dejah_thoris.webp', ARRAY[]::TEXT[]),
('character_dr_watson', 'Dr. Watson', 'ERB', 'Dr. Watson character from ERB', 2, 6, 3, 5, 'characters/062_dr_watson.webp', ARRAY[]::TEXT[]),
('character_dracula', 'Dracula', 'ERB', 'Dracula character from ERB', 4, 4, 6, 8, 'characters/069_dracula.webp', ARRAY[]::TEXT[]),
('character_headless_horseman', 'Headless Horseman', 'ERB', 'Headless Horseman character from ERB', 6, 4, 7, 2, 'characters/076_headless_horseman.webp', ARRAY[]::TEXT[]),
('character_hercules', 'Hercules', 'ERB', 'Hercules character from ERB', 3, 6, 8, 4, 'characters/083_hercules.webp', ARRAY[]::TEXT[]),
('character_invisible_man', 'Invisible Man', 'ERB', 'Invisible Man character from ERB', 2, 5, 3, 6, 'characters/090_invisible_man.webp', ARRAY[]::TEXT[]),
('character_jane_porter', 'Jane Porter', 'ERB', 'Jane Porter character from ERB', 3, 4, 3, 6, 'characters/097_jane_porter.webp', ARRAY[]::TEXT[]),
('character_joan_of_arc', 'Joan of Arc', 'ERB', 'Joan of Arc character from ERB', 2, 5, 2, 7, 'characters/104_joan_of_arc.webp', ARRAY[]::TEXT[]),
('character_john_carter_of_mars', 'John Carter of Mars', 'ERB', 'John Carter of Mars character from ERB', 2, 6, 7, 5, 'characters/111_john_carter_of_mars.webp', ARRAY[]::TEXT[]),
('character_king_arthur', 'King Arthur', 'ERB', 'King Arthur character from ERB', 3, 7, 4, 6, 'characters/118_king_arthur.webp', ARRAY[]::TEXT[]),
('character_korak', 'Korak', 'ERB', 'Korak character from ERB', 2, 6, 5, 6, 'characters/125_korak.webp', ARRAY[]::TEXT[]),
('character_lancelot', 'Lancelot', 'ERB', 'Lancelot character from ERB', 2, 7, 5, 4, 'characters/132_lancelot.webp', ARRAY[]::TEXT[]),
('character_leonidas', 'Leonidas', 'ERB', 'Leonidas character from ERB', 1, 8, 5, 4, 'characters/139_leonidis.webp', ARRAY[]::TEXT[]),
('character_merlin', 'Merlin', 'ERB', 'Merlin character from ERB', 7, 2, 2, 6, 'characters/146_merlin.webp', ARRAY[]::TEXT[]),
('character_mina_harker', 'Mina Harker', 'ERB', 'Mina Harker character from ERB', 6, 2, 6, 2, 'characters/153_mina_harker.webp', ARRAY[]::TEXT[]),
('character_morgan_le_fay', 'Morgan le Fay', 'ERB', 'Morgan le Fay character from ERB', 7, 2, 3, 5, 'characters/160_morgan_le_fay.webp', ARRAY[]::TEXT[]),
('character_mr_hyde', 'Mr. Hyde', 'ERB', 'Mr. Hyde character from ERB', 3, 5, 6, 6, 'characters/167_mr_hyde.webp', ARRAY[]::TEXT[]),
('character_poseidon', 'Poseidon', 'ERB', 'Poseidon character from ERB', 7, 2, 7, 5, 'characters/174_poseidon.webp', ARRAY[]::TEXT[]),
('character_professor_moriarty', 'Professor Moriarty', 'ERB', 'Professor Moriarty character from ERB', 3, 5, 4, 8, 'characters/181_professor_moriarty.webp', ARRAY[]::TEXT[]),
('character_ra', 'Ra', 'ERB', 'Ra character from ERB', 8, 2, 5, 5, 'characters/188_ra.webp', ARRAY[]::TEXT[]),
('character_robin_hood', 'Robin Hood', 'ERB', 'Robin Hood character from ERB', 2, 7, 4, 5, 'characters/195_robin_hood.webp', ARRAY[]::TEXT[]),
('character_sheriff_of_nottingham', 'Sheriff of Nottingham', 'ERB', 'Sheriff of Nottingham character from ERB', 2, 5, 7, 3, 'characters/202_sheriff_of_nottingham.webp', ARRAY[]::TEXT[]),
('character_sherlock_holmes', 'Sherlock Holmes', 'ERB', 'Sherlock Holmes character from ERB', 2, 5, 3, 8, 'characters/209_sherlock_holmes.webp', ARRAY[]::TEXT[]),
('character_sun_wukong', 'Sun Wukong', 'ERB', 'Sun Wukong character from ERB', 5, 8, 6, 3, 'characters/216_sun_wukong.webp', ARRAY[]::TEXT[]),
('character_tars_tarkas', 'Tars Tarkas', 'ERB', 'Tars Tarkas character from ERB', 2, 7, 6, 3, 'characters/223_tars_tarkas.webp', ARRAY[]::TEXT[]),
('character_tarzan', 'Tarzan', 'ERB', 'Tarzan character from ERB', 1, 7, 5, 4, 'characters/230_tarzan.webp', ARRAY[]::TEXT[]),
('character_the_mummy', 'The Mummy', 'ERB', 'The Mummy character from ERB', 6, 2, 7, 2, 'characters/237_the_mummy.webp', ARRAY[]::TEXT[]),
('character_three_musketeers', 'The Three Musketeers', 'ERB', 'The Three Musketeers character from ERB', 2, 7, 5, 5, 'characters/244_three_musketeers.webp', ARRAY[]::TEXT[]),
('character_time_traveler', 'Time Traveler', 'ERB', 'Time Traveler character from ERB', 5, 3, 2, 6, 'characters/251_time_traveler.webp', ARRAY[]::TEXT[]),
('character_van_helsing', 'Van Helsing', 'ERB', 'Van Helsing character from ERB', 3, 7, 4, 5, 'characters/258_van_helsing.webp', ARRAY[]::TEXT[]),
('character_victory_harben', 'Victory Harben', 'ERB', 'Victory Harben character from ERB', 5, 5, 3, 7, 'characters/265_victory_harben.webp', ARRAY[]::TEXT[]),
('character_wicked_witch', 'Wicked Witch', 'ERB', 'Wicked Witch character from ERB', 8, 3, 2, 5, 'characters/272_wicked_witch.webp', ARRAY[]::TEXT[]),
('character_zeus', 'Zeus', 'ERB', 'Zeus character from ERB', 8, 3, 6, 5, 'characters/279_zeus.webp', ARRAY[]::TEXT[]),
('character_zorro', 'Zorro', 'ERB', 'Zorro character from ERB', 1, 8, 4, 5, 'characters/285_zorro.webp', ARRAY[]::TEXT[])
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  universe = EXCLUDED.universe,
  description = EXCLUDED.description,
  energy = EXCLUDED.energy,
  combat = EXCLUDED.combat,
  brute_force = EXCLUDED.brute_force,
  intelligence = EXCLUDED.intelligence,
  image_path = EXCLUDED.image_path,
  alternate_images = EXCLUDED.alternate_images;