-- V99__Populate_locations_data.sql

-- Populate locations table with data from overpower-erb-locations.md
INSERT INTO locations (id, name, universe, image_path, threat_level, special_ability) VALUES
(gen_random_uuid(), 'Dracula''s Armory', 'Dracula', 'draculas_armory.webp', 3, 'At the beginning of the game, place three unique Basic Universe cards, excluding "Any-Power," under Dracula''s Armory. Once per battle, you may remove one of these cards to combine it with a legal attack or defense.'),
(gen_random_uuid(), 'Spartan Training Ground', 'Spartan', 'spartan_training_ground.webp', 2, 'At the beginning of the game, place three unique Training Universe cards, excluding "Any-Power," under Spartan Training Ground. Once per battle, you may remove one of these cards to combine it with a legal attack or defense.'),
(gen_random_uuid(), 'The Round Table', 'King Arthur', 'the_round_table.webp', 0, 'The Round Table''s team may place 1 "Any Character" Special card to this homebase. The Round Table''s team may not place any other kinds of Special cards to The Round Table.'),
(gen_random_uuid(), 'Barsoom', 'John Carter', 'barsoom.webp', 0, 'Whenever a character on your team offensively plays a non-numerical Special card that increases 1 or more of their grids, you may fetch 1 Power card from the Draw Pile, useable by the character playing the Special card. May not be duplicate. Reshuffle Draw Pile. All of these Special cards are now considered to have a "remainder of game" effect and have the "remainder of game" text.'),
(gen_random_uuid(), 'Asclepieion', 'Hercules', 'asclepieion.webp', 0, 'Anytime an Asclepieion Character plays a card that successfully removes a hit(s) from permanent record, but not current battle, they may draw a card and may immediately make an attack. Discard duplicates.'),
(gen_random_uuid(), '221-B Baker St.', 'Sherlock Holmes', '221_b_baker_st.webp', 0, 'Any time the 221-B Baker St. team plays a card that Reveals, Sorts, or Looks at cards from Opponent''s hand or Draw Pile, you may choose one of those cards and discard it into the appropriate Discard Pile.'),
(gen_random_uuid(), 'Event Horizon: The Future', 'Time Traveler', 'event_horizon_the_future.webp', 1, 'During each Event Phase, draw a replacement card for each Event card in hand instead of only 1 Event card. Once you have replaced all Event cards, choose 1 Event card that will take effect that battle. All other Event cards are discarded as normal.'),
(gen_random_uuid(), 'The Land That Time Forgot', 'Tarzan', 'the_land_that_time_forgot.webp', 3, 'During the Post-Concession Phase, The Land that Time Forgot team may make 1 Power card attack after Opponent has conceded. For this game, when determining victory, Character KO counts before Mission cards.');
