/**
 * @jest-environment jsdom
 */

describe('Special Cards Table Column Removal', () => {
  let mockDocument: any;

  beforeEach(() => {
    // Mock DOM elements
    mockDocument = {
      getElementById: jest.fn(),
      createElement: jest.fn()
    };

    // Mock global document
    (global as any).document = mockDocument;
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('Table Header Structure', () => {
    it('should have correct number of columns in special cards table header', () => {
      // Mock table header HTML structure (current database view)
      const mockTableHeader = `
        <tr>
          <th>Image</th>
          <th></th>
          <th>Name</th>
          <th>Character</th>
          <th>Card Effect</th>
          <th>Icon</th>
          <th>Value</th>
          <th>Function</th>
        </tr>
      `;

      // Count the number of <th> elements
      const headerMatches = mockTableHeader.match(/<th>/g);
      expect(headerMatches).toHaveLength(8);
    });

    it('should contain Icon column in header', () => {
      const mockTableHeader = `
        <tr>
          <th>Image</th>
          <th></th>
          <th>Name</th>
          <th>Character</th>
          <th>Card Effect</th>
          <th>Icon</th>
          <th>Value</th>
          <th>Function</th>
        </tr>
      `;

      expect(mockTableHeader).toContain('Icon');
    });

    it('should not contain Card Type column in header', () => {
      const mockTableHeader = `
        <tr>
          <th>Image</th>
          <th></th>
          <th>Name</th>
          <th>Character</th>
          <th>Card Effect</th>
          <th>Icon</th>
          <th>Value</th>
          <th>Function</th>
        </tr>
      `;

      expect(mockTableHeader).not.toContain('Card Type');
    });
  });

  describe('Table Row Structure', () => {
    it('should have correct number of columns in special cards table rows', () => {
      // Mock table row HTML structure in current DBV
      const mockTableRow = `
        <tr>
          <td><img src="..." alt="Card Name"></td>
          <td><button class="add-to-deck-btn">+Deck</button></td>
          <td><strong>Card Name</strong></td>
          <td>Character Name</td>
          <td>Card Effect Description</td>
          <td>Energy</td>
          <td>4</td>
          <td>Function Icons</td>
        </tr>
      `;

      // Count the number of <td> elements
      const rowMatches = mockTableRow.match(/<td>/g);
      expect(rowMatches).toHaveLength(8);
    });

    it('should not contain card_type data in table rows', () => {
      const mockTableRow = `
        <tr>
          <td><img src="..." alt="Card Name"></td>
          <td><button class="add-to-deck-btn">+Deck</button></td>
          <td><strong>Card Name</strong></td>
          <td>Character Name</td>
          <td>Card Effect Description</td>
          <td>Energy</td>
          <td>4</td>
          <td>Function Icons</td>
        </tr>
      `;

      expect(mockTableRow).not.toContain('${card.card_type}');
      expect(mockTableRow).not.toContain('undefined');
    });
  });

  describe('Loading Message Structure', () => {
    it('should have correct colspan for loading message', () => {
      const mockLoadingRow = `
        <tr>
          <td colspan="8" class="loading">Loading special cards...</td>
        </tr>
      `;

      expect(mockLoadingRow).toContain('colspan="8"');
    });

    it('should not use outdated colspan values for loading message', () => {
      const mockLoadingRow = `
        <tr>
          <td colspan="8" class="loading">Loading special cards...</td>
        </tr>
      `;

      expect(mockLoadingRow).not.toContain('colspan="7"');
      expect(mockLoadingRow).not.toContain('colspan="6"');
      expect(mockLoadingRow).not.toContain('colspan="5"');
    });
  });

  describe('Filter Row Structure', () => {
    it('should have correct number of filter cells', () => {
      const mockFilterRow = `
        <tr class="filter-row">
          <th><button class="clear-filters-btn">Clear All Filters</button></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      `;

      // Count the number of <th> elements in filter row
      const filterMatches = mockFilterRow.match(/<th>/g);
      expect(filterMatches).toHaveLength(8);
    });
  });

  describe('HTML Template Validation', () => {
    it('should validate that displaySpecialCards function generates correct HTML structure', () => {
      // Mock the HTML template that would be generated by displaySpecialCards
      const mockCard = {
        id: 'test-card-id',
        name: 'Test Card',
        character: 'Test Character',
        card_effect: 'Test Effect',
        image: 'test-image.webp'
      };

      // This is the template that should be generated (without card_type)
      const expectedTemplate = `
        <td>
          <img src="/src/resources/cards/images/specials/${mockCard.image}" 
               alt="${mockCard.name}" 
               style="width: 120px; height: auto; max-height: 180px; object-fit: contain; border-radius: 5px; border: 1px solid rgba(255, 255, 255, 0.2); cursor: pointer;">
        </td>
        <td>
          <button class="add-to-deck-btn" onclick="showDeckSelection('special', '${mockCard.id}', '${mockCard.name}', this)">
            Add to Deck
          </button>
        </td>
        <td><strong>${mockCard.name}</strong></td>
        <td>${mockCard.character}</td>
        <td>${mockCard.card_effect}</td>
        <td>4</td>
        <td>Function Icons</td>
      `;

      // Verify the template doesn't contain card_type
      expect(expectedTemplate).not.toContain('${card.card_type}');
      expect(expectedTemplate).not.toContain('card_type');
      
      // Verify it contains the expected structure
      expect(expectedTemplate).toContain('Test Card');
      expect(expectedTemplate).toContain('Test Character');
      expect(expectedTemplate).toContain('Test Effect');
    });
  });

  describe('Column Count Consistency', () => {
    it('should have consistent column count across all table elements', () => {
      const headerColumns = 8; // Image, Add to Deck, Name, Character, Card Effect, Icon, Value, Function
      const rowColumns = 8;    // Same as header
      const filterColumns = 8; // Same as header
      const loadingColspan = 8; // Matches the full table width in index.html

      expect(headerColumns).toBe(rowColumns);
      expect(headerColumns).toBe(filterColumns);
      expect(loadingColspan).toBe(headerColumns);
    });
  });
});
