/**
 * Card image URL resolution.
 *
 * Rules (preserved from the legacy site / API_V1 image contract):
 *  - Card art lives under `/src/resources/cards/images/<type>/[<subdir>/]<file>`.
 *  - In production a CDN base (from GET /api/v1/config/app) is prepended; in
 *    local dev the base is empty and Express static / the Vite proxy serve it.
 *  - Strip the trailing slash from the CDN base; the asset path keeps its
 *    leading slash. Never produce a double slash.
 *  - Thumbnails: insert `/thumb/` AFTER the type folder (so alternate-art
 *    subdirectories are preserved) and use the `.webp` extension. Thumbnails
 *    are generated by `npm run generate:thumbnails`.
 *  - Always resolve from the catalog `image` / `image_path` field; never guess
 *    from a card id.
 */
import type { CatalogCard, CatalogType } from '../api/types';
import { isLandscapeCatalogType } from '../catalog/catalogTypeMap';

const CARD_IMAGES_BASE = '/src/resources/cards/images';
const PLACEHOLDER = `${CARD_IMAGES_BASE}/placeholder.webp`;
const ASSET_MARKER = 'cards/images/';
export const SKYBOUND_CARD_BACK_PATH = 'sky/card-back/overpowerback.png';

let cdnBase = '';

export function setCdnBase(base: string | null | undefined): void {
  cdnBase = (base ?? '').replace(/\/+$/, '');
}

export function getCdnBase(): string {
  return cdnBase;
}

function isAbsolute(url: string): boolean {
  return /^https?:\/\//i.test(url) || url.startsWith('data:');
}

const TYPE_FOLDER_PREFIXES = [
  'characters/',
  'missions/',
  'specials/',
  'locations/',
  'events/',
  'aspects/',
  'power-cards/',
  'teamwork-universe/',
  'ally-universe/',
  'training-universe/',
  'basic-universe/',
  'advanced-universe/',
] as const;

/**
 * Location catalog rows store bare filenames or `alternate/...` without a
 * `locations/` prefix (legacy DB shape). Normalise before URL resolution.
 */
export function normalizeRawImagePath(
  raw: string | null | undefined,
  catalogType?: CatalogType,
): string {
  if (!raw || isAbsolute(raw)) return raw || '';

  if (catalogType !== 'locations') return raw;

  const badAbsoluteAlternate = raw.match(/^\/src\/resources\/cards\/images\/alternate\/(.+)$/);
  if (badAbsoluteAlternate) {
    return `/src/resources/cards/images/locations/alternate/${badAbsoluteAlternate[1]}`;
  }

  const badRelativeAlternate = raw.match(/^(src\/resources\/cards\/images\/)alternate\/(.+)$/);
  if (badRelativeAlternate) {
    return `/src/resources/cards/images/locations/alternate/${badRelativeAlternate[2]}`;
  }

  const rel = raw.replace(/^\/+/, '');
  if (rel.startsWith('locations/') || rel.startsWith('src/resources/cards/images/locations/')) {
    return raw;
  }

  // Set-scoped art keeps the card type as its second segment (e.g.
  // sky/locations/348_global_defense_agency.png).
  if (/^[^/]+\/locations\//i.test(rel)) return raw;

  if (!rel.includes('/')) {
    return `locations/${rel}`;
  }

  const hasTypePrefix = TYPE_FOLDER_PREFIXES.some((prefix) => rel.startsWith(prefix));
  if (!hasTypePrefix) {
    return `locations/${rel}`;
  }

  return raw;
}

/** Normalise a raw card path into a site-absolute asset path (no CDN yet). */
function toAssetPath(raw: string): string {
  if (!raw) return PLACEHOLDER;
  if (isAbsolute(raw)) return raw;
  let path = raw.replace(/^\/+/, '');
  if (path.startsWith('src/resources/')) {
    path = `/${path}`;
  } else {
    // Bare relative path such as "characters/foo.webp".
    path = `${CARD_IMAGES_BASE}/${path}`;
  }
  return path;
}

function applyCdn(assetPath: string): string {
  if (isAbsolute(assetPath)) return assetPath;
  return cdnBase ? `${cdnBase}${assetPath}` : assetPath;
}

/** Insert `/thumb/` after the type folder and switch to `.webp`. */
function thumbify(raw: string): string {
  if (!raw || isAbsolute(raw)) return raw;
  if (raw.includes('/thumb/')) return raw;

  const idx = raw.indexOf(ASSET_MARKER);
  let prefix = '';
  let rel = raw.replace(/^\/+/, '');
  if (idx >= 0) {
    prefix = raw.slice(0, idx + ASSET_MARKER.length);
    rel = raw.slice(idx + ASSET_MARKER.length);
  }

  const parts = rel.split('/');
  if (parts.length < 2) return raw; // cannot determine type folder
  const type = parts[0];
  const rest = parts.slice(1).join('/').replace(/\.[a-z0-9]+$/i, '.webp');
  return `${prefix}${type}/thumb/${rest}`;
}

export function imagePathFromCard(card: Partial<CatalogCard> | null | undefined): string {
  if (!card) return '';
  if (isSkyboundHiddenArtCard(card)) return SKYBOUND_CARD_BACK_PATH;
  return (card.image_path as string) || (card.image as string) || '';
}

/** Defense-in-depth for unreleased Skybound alternate art. */
export function isSkyboundHiddenArtCard(
  card: Partial<CatalogCard> | null | undefined,
): boolean {
  if (!card || String(card.set ?? '').trim().toUpperCase() !== 'SKY') return false;
  const match = String(card.set_number ?? '').trim().match(/^(\d+)/);
  if (!match) return false;
  const collectorNumber = Number.parseInt(match[1], 10);
  return collectorNumber >= 419 && collectorNumber <= 472;
}

/** True for the protected Skybound back asset regardless of path prefix or CDN base. */
export function isSkyboundCardBackPath(path: string | null | undefined): boolean {
  if (!path) return false;
  const normalized = path.split(/[?#]/, 1)[0].replace(/\\/g, '/').replace(/^\/+/, '');
  return normalized === SKYBOUND_CARD_BACK_PATH
    || normalized.endsWith(`/${SKYBOUND_CARD_BACK_PATH}`);
}

/** Landscape card frames rotate the portrait protected-art back counter-clockwise. */
export function shouldRotateSkyboundCardBack(
  path: string | null | undefined,
  catalogType?: CatalogType,
): boolean {
  return Boolean(catalogType && isLandscapeCatalogType(catalogType) && isSkyboundCardBackPath(path));
}

/** Known two-faced card fallback for surfaces that only carry an image path. */
export function reverseImagePathForImagePath(
  imagePath: string | null | undefined,
): string | null {
  if (!imagePath || !/(^|\/)sky\/characters\/226_walkers_herd\.png$/i.test(imagePath)) {
    return null;
  }
  return imagePath.replace(/226_walkers_herd\.png$/i, '226_walkers.png');
}

/** Full-resolution image URL (detail slide-out, deck card view, hero). */
export function resolveImageUrl(
  raw: string | null | undefined,
  catalogType?: CatalogType,
): string {
  const normalized = normalizeRawImagePath(raw, catalogType);
  return applyCdn(toAssetPath(normalized || ''));
}

/** Thumbnail URL (lists, tiles, ribbons). */
export function resolveThumbUrl(
  raw: string | null | undefined,
  catalogType?: CatalogType,
): string {
  const normalized = normalizeRawImagePath(raw, catalogType);
  if (!normalized) return applyCdn(PLACEHOLDER);
  return applyCdn(toAssetPath(thumbify(normalized)));
}

/** True when a distinct thumbnail path exists (thumb → full progressive load applies). */
export function canProgressiveLoad(
  raw: string | null | undefined,
  catalogType?: CatalogType,
): boolean {
  const normalized = normalizeRawImagePath(raw, catalogType);
  if (!normalized || isAbsolute(normalized) || normalized.includes('/thumb/')) return false;
  const thumbAsset = toAssetPath(thumbify(normalized));
  const fullAsset = toAssetPath(normalized);
  return thumbAsset !== fullAsset;
}

/** Compare a resolved asset URL to an in-DOM img (browser normalizes src to absolute). */
export function imageElementMatchesUrl(img: HTMLImageElement, url: string): boolean {
  if (!url || !img.src) return false;
  if (img.src === url) return true;
  try {
    const actualPath = new URL(img.src, 'http://localhost').pathname;
    const expectedPath = isAbsolute(url)
      ? new URL(url).pathname
      : url.startsWith('/')
        ? url.split('?')[0]
        : `/${url.split('?')[0]}`;
    return actualPath === expectedPath;
  } catch {
    return img.src.endsWith(url);
  }
}

export function cardImageUrl(card: Partial<CatalogCard> | null | undefined): string {
  return resolveImageUrl(imagePathFromCard(card));
}

export function cardThumbUrl(card: Partial<CatalogCard> | null | undefined): string {
  return resolveThumbUrl(imagePathFromCard(card));
}

export const placeholderImageUrl = (): string => applyCdn(PLACEHOLDER);

/**
 * Resolve a non-card UI asset under /src/resources/images/** (logo, icons,
 * backgrounds). These are committed + synced to the CDN like card art, so the
 * same CDN base applies.
 */
export function assetUrl(path: string): string {
  if (!path) return '';
  if (isAbsolute(path)) return path;
  const normalised = path.startsWith('/') ? path : `/${path}`;
  return cdnBase ? `${cdnBase}${normalised}` : normalised;
}
